Repository dlt-hub/verified-sources, pull requests merged in 2024-05, with the labels that each got.

#442 Updated sql_database comments
  sources/sql_database_pipeline.py
Labels: community

#456 Updates resource base config in rest api
  Makefile
  poetry.lock
  pyproject.toml
  sources/filesystem/readers.py
  sources/inbox/helpers.py
  sources/pg_replication/__init__.py
  sources/pg_replication/helpers.py
  sources/rest_api/__init__.py
  sources/rest_api/config_setup.py
  sources/rest_api/exceptions.py
  sources/rest_api/typing.py
  sources/rest_api_pipeline.py
  sources/unstructured_data/inbox/__init__.py
  sources/unstructured_data/inbox/helpers.py
  tests/rest_api/source_configs.py
  tests/rest_api/test_configurations.py
  tests/rest_api/test_rest_api_source_offline.py
Labels: sprint

#462 rest_api: add comments to example pipeline
  sources/rest_api_pipeline.py
Labels: sprint

#463 rest_api: fix BearerTokenAuthConfig shorthand typing
  sources/rest_api/typing.py
  sources/rest_api_pipeline.py
  tests/rest_api/source_configs.py
Labels: sprint

#464 rest_api: update example to use a decorator
  sources/rest_api_pipeline.py
Labels: sprint

#465 rest_api: adds custom exceptions, some edge cases and tests
  sources/rest_api/__init__.py
  sources/rest_api/config_setup.py
  sources/rest_api_pipeline.py
  tests/rest_api/source_configs.py
  tests/rest_api/test_configurations.py
Labels: sprint

#449 Use RESTClient in generic template
  init/pipeline.py
  init/pipeline_generic.py
Labels: enhancement, sprint

#432 Updated pipedrive README.md
  sources/pipedrive/README.md
Labels: community

#471 reset_api: allow JSONPath in field value in ResolveParamConfig
  sources/rest_api/config_setup.py
  sources/rest_api/typing.py
  tests/rest_api/test_configurations.py
Labels: enhancement
